"""Render the weekly ops report.

Two modes:
  1. **Deterministic** (no API key): fills a markdown template with computed
     KPIs and the top 3 root-cause families. Always works.
  2. **LLM-narrative** (if ANTHROPIC_API_KEY is set): asks Claude to write a
     few paragraphs of analyst-voice narrative grounded in the same structured
     KPI dict. The structured numbers always come first; the LLM only writes
     the prose section.

The split matters: structured KPIs are auditable and verifiable; the LLM
narrative is for context, not facts. This is how real ops platforms
(Datadog, Honeycomb) increasingly do incident summaries — fact-grounded LLMs
on top of deterministic aggregates.
"""
from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path

import pandas as pd

# Auto-load .env from the project root if python-dotenv is installed.
try:
    from dotenv import load_dotenv  # type: ignore
    # override=True so an empty parent-shell value can't shadow .env
    load_dotenv(Path(__file__).resolve().parents[3] / ".env", override=True)
except ImportError:
    pass

from gridsentinel.correlation.correlate import correlate
from gridsentinel.correlation.dedupe import dedupe
from gridsentinel.forecast.capacity import headroom_pct, weeks_to_exhaustion
from gridsentinel.forecast.utilization import forecast_gpu_hours, hourly_gpu_hours
from gridsentinel.ingest.telemetry import (
    enrich_with_topology,
    load_events,
    load_fleet,
    load_utilization,
)
from gridsentinel.kpi.efficiency import fleet_energy_summary
from gridsentinel.kpi.sla import alert_compression_ratio, noise_rate
from gridsentinel.rootcause.cluster import cluster_incidents, top_recurring
from gridsentinel.rootcause.features import featurize

REPORTS_DIR = Path(__file__).resolve().parents[3] / "data" / "reports"

_TEMPLATE = """# GridSentinel Weekly Ops Report — {week}

_Generated {generated_at} · {narrative_mode}_

## SLA snapshot
| Metric | Value |
|---|---|
| Raw events | {raw_events:,} |
| Correlated incidents | {incidents:,} |
| Alert compression | **{compression:.1f}×** |
| Critical incidents | {critical:,} |
| Noise rate (raw) | {noise_rate:.1%} |

## Top recurring root-cause families
{top_clusters_table}

## Capacity outlook (next {horizon_hours} hours)
| Metric | Value |
|---|---|
| Fleet capacity | {capacity:,} GPU-h/h |
| Current headroom | {headroom:.1%} |
| Weeks to 70% load | {weeks_to_70} |

## Energy & efficiency
| Metric | Value |
|---|---|
| Avg fleet draw | {avg_kw:,.0f} kW |
| Total energy this period | {total_kwh:,.0f} kWh |
| Idle energy waste | {idle_kwh:,.0f} kWh (${idle_dollars:,.0f}) |
| Performance per Watt | {perf_w:.4f} TFLOPS/W |

## Narrative
{narrative}

---
*Report generated by GridSentinel. Numbers above are deterministic
aggregates; the narrative section is {narrative_source}.*
"""


def _llm_narrative(kpis: dict, top_clusters: pd.DataFrame) -> str | None:
    """If ANTHROPIC_API_KEY is set, ask Claude to write 2-3 paragraphs.

    Returns None if the SDK isn't installed or the key isn't set — caller
    falls back to the deterministic narrative. Other errors (rate limits,
    network failures) raise so they're visible to the operator rather than
    silently degrading report quality.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        return None
    try:
        import anthropic  # type: ignore
    except ImportError:
        return None

    model = os.environ.get("ANTHROPIC_MODEL", "claude-haiku-4-5-20251001")
    clusters_summary = "\n".join(
        f"- {row.cluster_label}: {row['count']} incidents"
        for _, row in top_clusters.head(5).iterrows()
    )
    # Labelled KPI block with explicit units — prevents the model from
    # mislabelling values (e.g. reading TFLOPS/W as a utilization %).
    labels: dict[str, tuple[str, str]] = {
        "raw_events": ("Raw telemetry events", ""),
        "incidents": ("Correlated incidents", ""),
        "compression": ("Alert compression ratio (raw / incidents)", "×"),
        "critical": ("Critical-severity incidents", ""),
        "noise_rate": ("Raw-event noise rate", " (fraction benign)"),
        "capacity": ("Fleet capacity (peak GPU-hours per hour)", " GPU-h/h"),
        "headroom": ("Current capacity headroom", " (fraction unused)"),
        "weeks_to_70": ("Forecast weeks until 70% sustained load", " weeks"),
        "horizon_hours": ("Forecast horizon length", " hours"),
        "avg_kw": ("Average fleet electrical power draw", " kW"),
        "total_kwh": ("Total electrical energy consumed", " kWh"),
        "idle_kwh": ("Energy drawn by idle GPUs (util < 5%)", " kWh"),
        "idle_dollars": ("Idle-energy opportunity cost", " USD"),
        "perf_w": ("Performance per Watt (compute efficiency)", " TFLOPS/W"),
    }
    kpi_block = "\n".join(
        f"  {labels[k][0]}: {kpis[k]}{labels[k][1]}" for k in labels if k in kpis
    )
    prompt = f"""You are a data center operations analyst writing a weekly report
for stakeholders. Write 2-3 short paragraphs based ONLY on the labelled KPIs
below — do not invent numbers or events. Use the LABELS for each value so you
don't confuse units (e.g. TFLOPS/W is compute efficiency, NOT utilization %).

Cover: (1) what the headline numbers say about the week, (2) the top recurring
root-cause family and what it likely means for preventive action, (3) the
energy/efficiency angle especially around idle waste under a renewable PPA
(this fleet is renewable-powered).

Voice: concise, factual, analyst-not-marketer. No bullet points; flowing prose.
Do not introduce yourself or describe what you're about to do. Start directly
with the analysis.

== KPIs (labelled with units) ==
{kpi_block}

== Top root-cause families ==
{clusters_summary}
"""
    client = anthropic.Anthropic(api_key=api_key)
    resp = client.messages.create(
        model=model,
        max_tokens=600,
        messages=[{"role": "user", "content": prompt}],
    )
    text = "".join(block.text for block in resp.content if hasattr(block, "text"))
    return text.strip() or None


def _deterministic_narrative(kpis: dict, top_clusters: pd.DataFrame) -> str:
    top = top_clusters.iloc[0] if len(top_clusters) else None
    parts = [
        f"The fleet processed {kpis['raw_events']:,} raw telemetry events this period, "
        f"compressed to {kpis['incidents']:,} correlated incidents — a "
        f"{kpis['compression']:.1f}× reduction in alert volume. "
        f"{kpis['critical']:,} of those reached critical severity.",
    ]
    if top is not None:
        parts.append(
            f"The most frequent root-cause family was **{top['cluster_label']}** "
            f"with {top['count']} incidents. "
            "Recurring patterns at this volume are candidates for preventive action "
            "(workload rebalancing, predictive maintenance, or topology change)."
        )
    parts.append(
        f"Energy draw averaged {kpis['avg_kw']:,.0f} kW over the period; "
        f"{kpis['idle_kwh']:,.0f} kWh was consumed by idle GPUs, "
        f"representing ${kpis['idle_dollars']:,.0f} of avoidable spend "
        "and an equivalent amount of clean energy not converted into work."
    )
    return "\n\n".join(parts)


def _build_kpis() -> tuple[dict, pd.DataFrame]:
    events = load_events()
    fleet = load_fleet()
    util = load_utilization()
    enriched = enrich_with_topology(events, fleet)
    deduped = dedupe(enriched, window_ticks=5)
    incidents = correlate(deduped, time_window_ticks=15)
    feats = featurize(incidents)
    clustered = cluster_incidents(feats, incidents, min_cluster_size=8)
    top_clusters = top_recurring(clustered, n=10)

    hourly = hourly_gpu_hours(util)
    horizon_hours = 28 * 24  # 4-week outlook
    forecast = forecast_gpu_hours(hourly, horizon_hours=horizon_hours)
    capacity = float(fleet["node_id"].nunique() * 8)
    weeks = weeks_to_exhaustion(forecast, capacity, threshold=0.70)
    energy = fleet_energy_summary(util)

    kpis = {
        "raw_events": len(events),
        "incidents": len(incidents),
        "compression": alert_compression_ratio(len(events), len(incidents)),
        "critical": int((incidents["severity_max"] == "critical").sum()),
        "noise_rate": noise_rate(int(events["benign"].sum()), len(events)),
        "capacity": int(capacity),
        "headroom": headroom_pct(float(hourly.mean()), capacity),
        "weeks_to_70": "∞" if weeks is None else f"{weeks:.1f}",
        "horizon_hours": horizon_hours,
        "avg_kw": energy["avg_fleet_kw"],
        "total_kwh": energy["total_kwh"],
        "idle_kwh": energy["idle_kwh"],
        "idle_dollars": energy["idle_waste_dollars"],
        "perf_w": energy["perf_per_watt_tflops"],
    }
    return kpis, top_clusters


def render_weekly(week: str | None = None) -> Path:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    kpis, top_clusters = _build_kpis()

    narrative = _llm_narrative(kpis, top_clusters)
    narrative_mode = "LLM-narrative mode" if narrative else "Deterministic mode"
    narrative_source = "LLM-authored from the structured KPIs" if narrative else "template-rendered"
    if narrative is None:
        narrative = _deterministic_narrative(kpis, top_clusters)

    table_md = top_clusters.head(5)[
        ["cluster_label", "count", "critical_count", "all_benign_ratio"]
    ].to_markdown(index=False)

    body = _TEMPLATE.format(
        week=week or datetime.now().strftime("%Y-W%V"),
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        narrative_mode=narrative_mode,
        narrative_source=narrative_source,
        top_clusters_table=table_md,
        narrative=narrative,
        **kpis,
    )
    path = REPORTS_DIR / f"weekly_{week or datetime.now().strftime('%Y-W%V')}.md"
    path.write_text(body)
    return path


if __name__ == "__main__":
    p = render_weekly()
    print(f"wrote {p}")
